unity_command:
  initial_commands: [
    '$(arg unity_namespace)Settings set_frame_rate 30',
    '$(arg unity_namespace)Clock realtime false',
    '$(arg unity_namespace)Spawner load /home/jciardullo/Unity/Projects/Tutorial/Assets/AssetBundles/tutorial',
    '$(arg unity_namespace)Spawner scene Assets/Scenes/Tutorial',
    '$(arg unity_namespace)Settings configure GuaranteeFrameRate:true'
  ]

use_sim_time: true
