unity_command:
  initial_commands: [
    '$(arg unity_namespace)Settings set_frame_rate 30',
    '$(arg unity_namespace)Clock realtime false',
    '$(arg unity_namespace)Spawner load $(find scarab_unity)/environments/testoffice',
    '$(arg unity_namespace)Spawner scene Assets/Scenes/ModernOffice_Interior_SampleLayout',
    '$(arg unity_namespace)Settings configure GuaranteeFrameRate:true'
  ]

use_sim_time: true
